name: Build

on:
  push:
    branches: ["**"]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 6

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        distribution: 'adopt'
 
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/org/spigotmc
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}

    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
 
    - name: Build
      run: |
        mvn clean package "-Dversion=$(git describe --tags `git rev-list --tags --max-count=1`)--SNAPSHOT"
        mkdir dist
        mv target/twitchinteractions-*.jar ./dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Plugin
        path: dist/