name: Build

on:
  push:
    branches: ["**"]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set BUILD_VERSION
      run: echo "BUILD_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))-b$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Maven cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ vars.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ vars.CACHE_VERSION }}-
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Run BuildTools
      run: |
        bash ./.github/workflows/buildtools.sh
    - name: Build
      run: |
        mvn clean package --batch-mode -Dversion=$BUILD_VERSION
        mv target/twitchinteractions-*.jar ./

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Plugin
        path: ./twitchinteractions-*.jar